Use apt-archive repo keeping the container immutability
GoogleCloudPlatform/postgresql-docker pull request #77
Opened 2021-08-24 14:59 UTC by armandomiani

2021-08-24 17:37 UTC, ovk6 requested changes

2021-08-24 17:37 UTC, ovk6 commented on templates/Dockerfile.template
> +RUN apt-get update && apt-get install -y apt-transport-https ca-certificates
Move these packages together with other dependencies on L10

2021-08-27 08:28 UTC, cgn170 approved these changes

2021-08-27 09:45 UTC, ovk6 approved these changes

2021-08-27 10:06 UTC, merged